version: "3.9"
services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    volumes:
    - ./api/db/data:/var/lib/mysql
    restart: always  
    ports:
    - "3306"